POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo Evento 2",
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/18d40bf9-b90a-4dc3-a1fd-1748467cdf30/attendees
Content-Type: application/json

{
    "name": "Diego Fernandes",
    "email": "diego@rockeseat.com.br"
}

###

GET http://localhost:3333/events/18d40bf9-b90a-4dc3-a1fd-1748467cdf30

###

GET http://localhost:3333/attendees/3/badge